/**
 * Agent configuration: env, connection, region registry, PDA helpers.
 * All secrets come from the repo-root .env (never committed).
 */
import * as fs from "fs";
import * as path from "path";
import * as dotenv from "dotenv";
import { Connection, PublicKey, clusterApiUrl } from "@solana/web3.js";

dotenv.config({ path: path.resolve(__dirname, "..", "..", ".env") });

export const RPC_URL = process.env.RPC_URL || clusterApiUrl("devnet");
export const MODEL_API_URL = process.env.MODEL_API_URL || "http://localhost:8000";

export const PROGRAM_ID = new PublicKey(
  process.env.LEVEE_PROGRAM_ID || "GYMBo4SUqjSCvvN1Bzjmu5MPjFzt47GM3vVDZFM7sUMq"
);

// Path to the Anchor IDL (generated by `anchor build`).
export const PROGRAM_IDL_PATH =
  process.env.LEVEE_IDL_PATH ||
  path.resolve(__dirname, "..", "..", "program", "target", "idl", "levee.json");

export const AGENT_REGIONS = (process.env.AGENT_REGIONS || "1")
  .split(",")
  .map((s) => Number(s.trim()))
  .filter((n) => !Number.isNaN(n));

export const POLL_INTERVAL_SECONDS = Number(
  process.env.AGENT_POLL_INTERVAL_SECONDS || 60
);

/** Payouts whose TOTAL exceeds this (whole USDC) require human approval. */
export const HITL_APPROVAL_THRESHOLD_USDC = Number(
  process.env.HITL_APPROVAL_THRESHOLD_USDC || 2000
);

/** When true, never send payout/log transactions — plan/preview only. */
export const AGENT_DRY_RUN =
  (process.env.AGENT_DRY_RUN || "true").toLowerCase() === "true";

export const USDC_DECIMALS = 6;

export function getConnection(): Connection {
  return new Connection(RPC_URL, "confirmed");
}

// ---- shared region registry ----
interface RegionDef {
  region_id: number;
  slug: string;
  name: string;
  threshold_bps: number;
  payout_amount_usdc: number;
  cap_usdc: number;
  cooldown_seconds: number;
  static_susceptibility: number;
  [k: string]: unknown;
}
const regionsFile = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, "..", "..", "shared", "regions.json"), "utf-8")
) as { RISK_SCALE: number; regions: RegionDef[] };
export const RISK_SCALE = regionsFile.RISK_SCALE;
export function getRegionDef(regionId: number): RegionDef {
  const r = regionsFile.regions.find((x) => x.region_id === regionId);
  if (!r) throw new Error(`Unknown region_id=${regionId}`);
  return r;
}

// ---- PDA seeds (MUST match the Rust program) ----
export function regionSeedBytes(regionId: number): Buffer {
  const b = Buffer.alloc(2);
  b.writeUInt16LE(regionId, 0);
  return b;
}
function u64le(n: bigint): Buffer {
  const b = Buffer.alloc(8);
  b.writeBigUInt64LE(n, 0);
  return b;
}
export const pdaVault = () =>
  PublicKey.findProgramAddressSync([Buffer.from("vault")], PROGRAM_ID)[0];
export const pdaRegion = (id: number) =>
  PublicKey.findProgramAddressSync(
    [Buffer.from("region"), regionSeedBytes(id)],
    PROGRAM_ID
  )[0];
export const pdaRegistry = (id: number) =>
  PublicKey.findProgramAddressSync(
    [Buffer.from("beneficiaries"), regionSeedBytes(id)],
    PROGRAM_ID
  )[0];
export const pdaDecision = (id: number, sequence: bigint) =>
  PublicKey.findProgramAddressSync(
    [Buffer.from("decision"), regionSeedBytes(id), u64le(sequence)],
    PROGRAM_ID
  )[0];
